CUSTOM_IMAGE_MOUNT_POINT := oem
ifeq ($(TARGET_BUILD_KERNEL_4_9),true)
CUSTOM_IMAGE_PARTITION_SIZE := 14680064
else
CUSTOM_IMAGE_PARTITION_SIZE := 31457280
endif
CUSTOM_IMAGE_FILE_SYSTEM_TYPE := ext4
CUSTOM_IMAGE_DICT_FILE := device/khadas/kvim4/oem/oem_dict.txt
CUSTOM_IMAGE_SELINUX := true
CUSTOM_IMAGE_COPY_FILES := device/khadas/kvim4/oem/oem.prop:oem.prop